name: MaartenDrupsteen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70261
title: People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8c5c2'
    - '#fdfdfd'
    - '#4f462e'
    - '#757265'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
